# Generated by Django 6.1.1 on 2026-10-02 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre de Categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_cliente', models.CharField(choices=[('DETAL', 'Al Detal'), ('MAYORISTA', 'Mayorista')], default='DETAL', max_length=10, verbose_name='Tipo de Cliente')),
                ('cupo_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Cupo de Crédito')),
                ('puntos_fidelidad', models.IntegerField(default=0, verbose_name='Puntos de Fidelidad')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=150, verbose_name='Razón Social')),
                ('nit_rut', models.CharField(max_length=30, unique=True, verbose_name='NIT / RUT')),
                ('contacto_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de Contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo Electrónico')),
                ('calificacion_estrellas', models.DecimalField(decimal_places=1, default=5.0, max_digits=2, verbose_name='Calificación (Estrellas)')),
                ('estado', models.CharField(default='Activo', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('unidad_medida', models.CharField(default='kg', max_length=20, verbose_name='Unidad de Medida')),
                ('brix_minimo', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='°Brix Mínimo (Dulzor)')),
                ('stock_actual', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Stock Actual')),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Stock Mínimo')),
                ('precio_venta_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de Venta Unitario')),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Agotado', 'Agotado'), ('En Maduracion', 'En Maduración')], default='Disponible', max_length=20, verbose_name='Estado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='principal.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
            },
        ),
    ]
