# Generated by Django 6.1.1 on 2026-10-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='icono_emoji',
            field=models.CharField(default='🍎', max_length=10, verbose_name='Icono / Emoji'),
        ),
        migrations.AddField(
            model_name='producto',
            name='origen',
            field=models.CharField(default='🌱 Cosecha: Hace 1 día • Finca El Campo', max_length=150, verbose_name='Origen / Cosecha'),
        ),
    ]
