# Generated by Django 6.1.1 on 2026-10-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_producto_icono_emoji_producto_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Imagen'),
        ),
    ]
